
"""Test: consolidation JSON parsing with flat (no 'add' wrapper) model output.

Reproduces the bug where scraper-mode model returns:
  {"semantic": [...], "episodic": [...], "procedural": [...]}
but the code expects:
  {"add": {"semantic": [...], ...}, "delete": [...]}

The legacy fallback at line ~988 checks `not isinstance(adds, dict)` but
new_entries.get("add", {}) returns {} which IS a dict → fallback never fires.
"""

import json
import sys
from pathlib import Path

# The exact payload the scraper model returned
MODEL_OUTPUT = """
{
  "semantic": [
    {
      "key": "phantom_bot regex rewriter double prefix bug",
      "value": "Regex rewriter (app.py ~L125) rewrites absolute paths like href='/static/...' by prepending url_prefix. When url_for already generated prefixed paths (via SCRIPT_NAME), the regex added another prefix, breaking CSS loads. Fix: exclude paths already starting with url_prefix by adjusting regex pattern to r'((?:href|action|src)\\\\s*=\\\\s*\\\")(/(?!/|{url_prefix.lstrip('/')}/))'."
    },
    {
      "key": "phantom_bot homepage timeout MongoDB cold-start",
      "value": "Index page (/ or /panel/) executes ~6 parallel MongoDB count queries on load. When Atlas cold-start delays first connection, all queries hang and proxy (aiohttp) times out (502). Not yet fixed; potential solutions: reduce query count, add timeout handling, or warm-up connection before request."
    },
    {
      "key": "phantom_bot JS hardcoded path fix pattern",
      "value": "To fix JS files with hardcoded absolute paths under a url_prefix: 1) Pass url_prefix to template via render_template('...', url_prefix=url_prefix or ''). 2) In template before script tag, set window.URL_PREFIX = '{{ url_prefix }}'. 3) In JS, const P = window.URL_PREFIX || '' and prepend P to all absolute URL strings."
    },
    {
      "key": "phantom_bot admin API user fields",
      "value": "/admin/api/users endpoint now returns user_id, section, and status (mapped from is_admin boolean). JS in admin_panel.html expects these fields for rendering sec and id columns."
    },
    {
      "key": "phantom_bot routine editor JS file location",
      "value": "Routine editor JavaScript is at /home/sifat/hdd/projects/phantom_bot/web/static/js/editor.js. Contains hardcoded API_LOAD_BASE='/routine/data/' and API_SAVE_URL='/routine/save' which break under url_prefix."
    },
    {
      "key": "phantom_bot schedule route variable mismatches",
      "value": "schedule_index route originally passed schedule_types and docs (dict), but template expected types and schedules (flat list). schedule_add route was /schedule/add/<stype> expecting subject/date/note, but template POSTs to /schedule/add with type/subject/teacher/date/time/topic/syllabus. Fixed by rewriting routes to match template expectations."
    }
  ],
  "episodic": [
    {
      "key": "phantom_bot panel debugging marathon 2026-07-27",
      "value": "Debugged multiple issues with phantom_bot's panel under /panel url_prefix: admin panel redirect loop (hardcoded JS paths), schedule editor not loading (variable/form mismatches), CSS double prefix (regex rewriter), admin fields missing (API field mapping), routine editor not loading (hardcoded JS paths). All fixed except homepage timeout due to MongoDB Atlas cold-start on parallel count queries. Pattern emerged: any JS file with absolute fetch/redirect URLs must be prefixed-aware."
    }
  ],
  "procedural": [
    {
      "key": "Debugging phantom_bot cloudflare tunnel URL-prefix issues",
      "value": "When phantom_bot pages fail under a URL prefix (e.g., /panel), check: 1) JS files for hardcoded absolute paths (fetch, location.href) that lack prefix — inject url_prefix via template. 2) Server-side routes that render templates must pass url_prefix to enable JS prefixing. 3) Regex rewriter (for HTML attrs) must avoid double-prefixing paths already generated by url_for. 4) Homepage slowness: MongoDB Atlas cold-start can cause 502 if index route makes many parallel queries; consider connection warming or query reduction."
    }
  ]
}
"""


def simulate_current_logic(raw_answer: str) -> dict:
    """Replicate the exact parsing logic from server.py lines 963-992."""
    cleaned = raw_answer.strip()
    if cleaned.startswith("```"):
        lines = cleaned.split("\n")
        lines = [l for l in lines if not l.strip().startswith("```")]
        cleaned = "\n".join(lines).strip()

    try:
        new_entries = json.loads(cleaned)
    except json.JSONDecodeError:
        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start != -1 and end > start:
            new_entries = json.loads(cleaned[start : end + 1])
        else:
            return {"error": "No JSON found"}

    if not isinstance(new_entries, dict):
        return {"error": "Expected dict"}

    # --- THIS IS THE BUGGY SECTION (server.py ~L986-992) ---
    adds = new_entries.get("add", {})
    deletes = new_entries.get("delete", [])
    if not isinstance(adds, dict):
        # Legacy flat format fallback
        adds = {k: v for k, v in new_entries.items() if k in ("semantic", "episodic", "procedural")}
        deletes = []
    if not isinstance(deletes, list):
        deletes = []

    # Count what would actually be added
    added = 0
    for cat in ("semantic", "episodic", "procedural"):
        new_list = adds.get(cat, [])
        if isinstance(new_list, list):
            added += len(new_list)

    return {"adds": adds, "deletes": deletes, "total_would_add": added}


def simulate_fixed_logic(raw_answer: str) -> dict:
    """Fixed version: detect flat format by checking if 'add' key is absent."""
    cleaned = raw_answer.strip()
    if cleaned.startswith("```"):
        lines = cleaned.split("\n")
        lines = [l for l in lines if not l.strip().startswith("```")]
        cleaned = "\n".join(lines).strip()

    try:
        new_entries = json.loads(cleaned)
    except json.JSONDecodeError:
        start = cleaned.find("{")
        end = cleaned.rfind("}")
        if start != -1 and end > start:
            new_entries = json.loads(cleaned[start : end + 1])
        else:
            return {"error": "No JSON found"}

    if not isinstance(new_entries, dict):
        return {"error": "Expected dict"}

    # --- FIXED: check if "add" key exists, not just if result is a dict ---
    if "add" in new_entries:
        adds = new_entries["add"]
        deletes = new_entries.get("delete", [])
    else:
        # Flat format: top-level keys ARE the categories
        adds = {k: v for k, v in new_entries.items() if k in ("semantic", "episodic", "procedural", "protected", "ephemeral")}
        deletes = []

    if not isinstance(adds, dict):
        adds = {}
    if not isinstance(deletes, list):
        deletes = []

    added = 0
    for cat in ("semantic", "episodic", "procedural", "protected", "ephemeral"):
        new_list = adds.get(cat, [])
        if isinstance(new_list, list):
            added += len(new_list)

    return {"adds": adds, "deletes": deletes, "total_would_add": added}


if __name__ == "__main__":
    print("=" * 60)
    print("TEST: Scraper model returns flat JSON (no 'add' wrapper)")
    print("=" * 60)

    print("\n--- CURRENT (buggy) logic ---")
    result_buggy = simulate_current_logic(MODEL_OUTPUT)
    print(f"  adds keys: {list(result_buggy.get('adds', {}).keys())}")
    print(f"  total entries that would be added: {result_buggy.get('total_would_add', 0)}")
    print(f"  deletes: {result_buggy.get('deletes', [])}")

    print("\n--- FIXED logic ---")
    result_fixed = simulate_fixed_logic(MODEL_OUTPUT)
    print(f"  adds keys: {list(result_fixed.get('adds', {}).keys())}")
    print(f"  total entries that would be added: {result_fixed.get('total_would_add', 0)}")
    print(f"  deletes: {result_fixed.get('deletes', [])}")

    print("\n" + "=" * 60)
    if result_buggy["total_would_add"] == 0 and result_fixed["total_would_add"] > 0:
        print("BUG CONFIRMED: current logic silently drops all entries.")
        print(f"  Expected: 8 entries (6 semantic + 1 episodic + 1 procedural)")
        print(f"  Current:  {result_buggy['total_would_add']}")
        print(f"  Fixed:    {result_fixed['total_would_add']}")
        sys.exit(0)
    else:
        print("UNEXPECTED: bug not reproduced or fix doesn't help.")
        sys.exit(1)
